config-service: 
  container_name: config-service
  image: mlabouardy/config-service
  ports: 
    - "9000:9000"
 
schedule-service: 
  container_name: schedule-service
  image: mlabouardy/schedule-service
  ports: 
    - "8080:8080"
  restart: always
  volumes: 
    - "$PWD/csv:/data"
    
scrapper-service: 
  container_name: scrapper-service
  image: mlabouardy/scrapper-service
  ports: 
    - "3000:3000"
  volumes: 
    - "$PWD/csv:/usr/src/app/csv"
